---
  - name: Configure virtualenvwrapper home directory and script path
    sudo: yes
    template:
      src: bash_profile.j2
      dest: ~/.bash_profile

  - name: Create and activate virtual web environment
    sudo: yes
    shell: "export WORKON_HOME=/vagrant/.venv && source $(which virtualenvwrapper.sh) && mkvirtualenv -a /vagrant/web -p $(which python) web && echo 'source .env' >> $WORKON_HOME/postactivate && echo 'pip install -r requirements.txt' >> $WORKON_HOME/postactivate && echo 'pip freeze > requirements.txt' >> $WORKON_HOME/postactivate"
    args:
      executable: /bin/bash
