---
  - name: Export BASH_PROFILE
    sudo: yes
    shell: bash -c "export BASH_PROFILE=~/.bashrc"

  - name: Configure virtualenvwrapper home directory if not already in BASH_PROFILE
    sudo: yes
    shell: bash -c "grep -q 'WORKON_HOME' $BASH_PROFILE || echo 'export WORKON_HOME=/vagrant/application/.venv' >> $BASH_PROFILE"

  - name: Configure the virtualenvwrapper script path if not already in BASH_PROFILE
    sudo: yes
    shell: bash -c "grep -q 'virtualenvwrapper.sh' BASH_PROFILE || echo 'source $(which virtualenvwrapper.sh)' >> $BASH_PROFILE"

  - name: Source the shell environment
    sudo: yes
    shell: bash -c "source $BASH_PROFILE"

  - name: create virtual environment|bind project|cd into project|activate virtual environment
    sudo: yes
    shell: bash -c "mkvirtualenv -a /vagrant/application/web -p $(which python) web"



















