---
  - lineinfile: dest=~/.bash_profile line='export WORKON_HOME=/vagrant/.venv'

  - lineinfile: dest=~/.bash_profile line='source $(which virtualenvwrapper.sh)'

  - lineinfile: dest=~/.bash_profile line="alias wo='workon'"

  - lineinfile: dest=~/.bash_profile line="alias da='deactivate'"

  - lineinfile: dest=~/.bash_profile line="alias run='python manage.py runserver'"

  - lineinfile: dest=~/.bash_profile line="alias gun='gunicorn -b 127.0.0.1:4000 manage:app'"

  - lineinfile: dest=~/.bash_profile line="alias pgstart='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'"

  - lineinfile: dest=~/.bash_profile line="alias pgstop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'"

  - lineinfile: dest=~/.bash_profile line="alias da='pip install -r requirements.txt'"

  - lineinfile: dest=~/.bash_profile line="alias da='pip freeze > requirements.txt'"

  - name: Create and activate python virtual environment bound to web project
    sudo: no
    shell: "export WORKON_HOME=/vagrant/.venv && source $(which virtualenvwrapper.sh) && mkvirtualenv -a /vagrant/web -p $(which python) web"
    args:
      executable: /bin/bash
      creates: /vagrant/.venv/postactivate

  - lineinfile: dest=/vagrant/.venv/postactivate line='echo Activating virtual environment'

  - lineinfile: dest=/vagrant/.venv/postactivate line='echo Exporting application environment variables'

  - lineinfile: dest=/vagrant/.venv/postactivate line='source .env'

  - lineinfile: dest=/vagrant/.venv/postactivate line='echo Installing requirements.txt packages'

  - lineinfile: dest=/vagrant/.venv/postactivate line='pip install -r requirements.txt'

  - lineinfile: dest=/vagrant/.venv/postactivate line='echo Freezing requirements.txt package dependencies'

  - lineinfile: dest=/vagrant/.venv/postactivate line='pip freeze > requirements.txt'

  - lineinfile: dest=/vagrant/.venv/postactivate line='echo Virtual environment activated'







