---
  - name: Configure virtualenvwrapper home directory and script path
    sudo: yes
    template:
      src: bash_profile.j2
      dest: ~/.bash_profile

  - name: Create and activate virtual web environment
    sudo: yes
    shell: "source $(which virtualenvwrapper.sh) && mkvirtualenv -a /vagrant/web -p $(which python) web"
    args:
      executable: /bin/bash
