---
  - name: Configure virtualenvwrapper home directory if not already in BASH_PROFILE
    sudo: yes
    shell: bash -c "grep -q 'WORKON_HOME' {{ bash_profile }} || echo 'export WORKON_HOME=/vagrant/.venv' >> {{ bash_profile }}"

  - name: Configure the virtualenvwrapper script path if not already in BASH_PROFILE
    sudo: yes
    shell: bash -c "grep -q 'virtualenvwrapper.sh' {{ bash_profile }} || echo 'source $(which virtualenvwrapper.sh)' >> {{ bash_profile }}"

  - name: Source the shell environment
    sudo: yes
    shell: bash -c "source {{ bash_profile }}"

  - name: create virtual environment|bind project|cd into project|activate virtual environment
    sudo: yes
    shell: bash -c "mkvirtualenv -a /vagrant/web -p $(which python) web"



















